### ISSUE TITLE
Request: S3 Transfer Acceleration

### ISSUE THREAD

**Issue by wvargas-ods** [rustyconover/net-amazon-s3#100]
I don't know if it already allows Transfer Acceleration, but I don't see any information about it, and would be nice to have:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html

**Comment by happy-barney** [comment]
Transfer Acceleration is supported only indirectly - when creating `Net::Amazon::S3` instance you have to create vendor instance with modified host
```
my $s3 = Net::Amazon::S3->new (
  vendor => Net::Amazon::S3::Vendor::Amazon->new (
    host => 's3-accelerate.amazonaws.com',
    use_virtual_host => 1,
  ),
);
```

**Comment by wvargas-ods** [comment]
Hey Barney, thanks for the reply. In the end, I didn't use the Transfer Acceleration, but good to know. I'll close this issue.
