### ISSUE TITLE
Net::Amazon::S3::Error::Handler - incorrect method names in POD

### ISSUE THREAD

**Issue by bbkr** [rustyconover/net-amazon-s3#101]
POD https://metacpan.org/pod/Net::Amazon::S3::Error::Handler states this class supports methods:
```
handler_error ($response)
handler_error ($response, $request)
```

While proper names to overwrite while implementing custom error handler are:
```
handle_error ($response)
handle_error ($response, $request)
```

**Comment by happy-barney** [comment]
Thanks for spotting this
