### ISSUE TITLE
Response etag from object->get is not always an md5

### ISSUE THREAD

**Issue by veryrusty** [rustyconover/net-amazon-s3#109]
We have S3 buckets that are encrypted with SSE-KMS. When you fetch those objects, the etag in the response is not an md5 checksum. See https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html 

Net::Amazon::S3 handles the case if the object is fetched that was added via multipart upload  (eg https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Client/Object.pm#L105-L110 ), but incorrectly throws "Corrupted download" errors if an SSE-KMS encrypted object is fetched.

**Comment by happy-barney** [comment]
Solved in #116 / release v0.99
