### ISSUE TITLE
Failed to enumerate buckets in a fake S3

### ISSUE THREAD

**Issue by Bu11etmagnet** [rustyconover/net-amazon-s3#11]
When getting the following response from a FakeS3 (https://github.com/jubos/fake-s3) instance:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Owner><ID>123</ID><DisplayName>FakeS3</DisplayName></Owner>
<Buckets><Bucket><Name>...
```

Net::Amazon::S3::Client::Bucket::new died with
`Attribute (owner_id) does not pass the type constraint because: Validation failed for 'OwnerId' with value 123 at constructor Net::Amazon::S3::Client::Bucket::new`

**Comment by rustyconover** [comment]
Hi,

OwnerIds are validated to:

`type 'OwnerId' => where { $_ =~ /^[a-z0-9]{64}$/ };`

If you make your OwnerId longer (64 characters) you shouldn't have a problem.  Or you can relax the regular expression in your branch.

HTH,

Rusty
