### ISSUE TITLE
How to do a ranged GET

### ISSUE THREAD

**Issue by fkoyer** [rustyconover/net-amazon-s3#113]
For working with large objects, it's desirable to download the object in chunks. AWS supports using the [HTTP byte range header](https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html) to accomplish this. I can't figure out how to do it with this library. Is it possible?

**Comment by happy-barney** [comment]
not quite easy at the moment.

you should be able to alter `$s3->ua->default_headers` (see `LWP::UserAgent` manpage) before each `GET` request.

**Comment by fkoyer** [comment]
Thanks for the quick response. It wasn't quite as easy as just altering the headers. It was failing because the md5 checksum of the partial download didn't match the etag value. It resulted in the following error:
```
Corrupted download at /usr/local/share/perl5/Net/Amazon/S3/Client/Object.pm line 108.
```
I created PR #115 to address the issue and added a get_range() method to simplify things.

**Comment by happy-barney** [comment]
#116 adds extra `range` parameter

**Comment by fkoyer** [comment]
Hi @happy-barney,

Thanks for implementing this. I'm just wondering why you decided to make the `range` method accept a string instead of a start & stop byte. In other words, `range("bytes=1024-10240")` instead of `range(1024,10240)`. I understand that's the format of the Range header in the AWS API, but IMHO the latter format is easier to understand, less error-prone, and will continue to work even if the underlying API changes at some point in the future. Just food for thought.

**Comment by happy-barney** [comment]
it's because of specification of `Range` header. Unit is not restricted to be `bytes` so `range(bytes => [1024, 10240])` will be necessary. Stop or start bytes doesn't need to be specified so `undef` should be possible. Also you can specify multiple start/stops in one header. Too many combinations at the moment so I rather implemented raw value support and postpone abstraction.

**Comment by fkoyer** [comment]
According to the HTTP specification, the Range header can specify multiple ranges however the Amazon API doesn't support it. See this page: https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

> Amazon S3 doesn't support retrieving multiple ranges of data per GET request.

I cannot find anything in the documentation about using a unit other than `bytes`. Do you have a reference to something different?

You are correct that start or stop can be omitted. This would be trivial to implement by just accepting `undef` as either parameter.

**Comment by happy-barney** [comment]
first, this library is not about AWS only, it should support multiple S3-like services - I'm sure there are some I'm not aware of. Same is for range. Currently only `bytes` and `none` are registered but nothing prevents you to implement vendor specific units. I just decided to provide lowest possible API (HTTP header value is string), and provide higher abstraction once I will have more info.

**Comment by fkoyer** [comment]
Ok. Thank you for the explanation
