### ISSUE TITLE
HeadBucket calls are heavily rate-limited

### ISSUE THREAD

**Issue by pborzenkov** [rustyconover/net-amazon-s3#117]
Hi!

Per the docs, `Net::Amazon::S3->bucket` call does no network access:

> Returns an (unverified) bucket object from an account. Does no network access.

This is slightly misleading, as it does `HeadBucket` operation to query the bucket's region (once).

The problem with this approach is that `HeadBucket` calls are heavily rate-limited by AWS (e.g. normal per-prefix rate-limits do not apply here) and with the above documentation it's quite easy to write a piece of code that creates a `Net::Amazon::S3::Bucket` object before each `PUT` or `GET`, basically doing `HeadBucket` call each time.

I suggest to either clarify this explicitly in the documentation, or to accept `region` as an argument do not query it implicitly anymore.

**Comment by happy-barney** [comment]
Thanks for reporting. `bucket` method now supports optional region
```
$s3->bucket ('foo', region => 'bar')
```
