### ISSUE TITLE
SignatureDoesNotMatch error when using tilde character (~) in key

### ISSUE THREAD

**Issue by marcusclip** [rustyconover/net-amazon-s3#119]
E.g. when uploading a file with ~ in the key / file name.

Issue is that ~ is being escaped when it shouldn't in _urlencode() in S3.pm

Fix is to include the ~ character in the exclude list to uri_escape_utf8() as follows:

    return uri_escape_utf8( $unencoded, '^A-Za-z0-9_\-\.\~' );

**Comment by happy-barney** [comment]
Thanks for reporting.
Will be uploaded to CPAN tomorrow, hope I will fix more issues.
