### ISSUE TITLE
Make VM::EC2::Security::CredentialCache an optional dependency

### ISSUE THREAD

**Issue by lasse-unity3d** [rustyconover/net-amazon-s3#12]
VM::EC2::Security::CredentialCache depends on VM::EC2 which in turn depends on AnyEvent and a whole bunch of other stuff. This seems a bit heavy for a feature that is never used if you just use a plain access_key_id/secret_access_key pair. Would you be willing to make it an optional dependency?

**Comment by jimbrowne** [comment]
Perhaps do what I did for https://github.com/mrallen1/net-amazon-ec2/pull/26?

**Comment by ranguard** [comment]
As a side note https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL has been released - testing would be appreciated

**Comment by branislav-zahradnik-gdc** [comment]
V:E:S:CredentialCache is now only optional dependency
