### ISSUE TITLE
Use of uninitialized value in concatenation (.) or string at Net/Amazon/S3/Signature/V4Implementation

### ISSUE THREAD

**Issue by ambs** [rustyconover/net-amazon-s3#127]
Sorry if I am doing anything pretty wrong, but I am new to AWS/S3, and to make it more difficult, working with Wasabi, making me less comfortable with what I am doing.

I am trying something in this line:

```perl

    $self->{auth} = Net::Amazon::S3::Authorization::Basic->new(
       aws_access_key_id => $self->{access_key},
       aws_secret_access_key => $self->{secret_key}
    );

     $self->{vendor} = Net::Amazon::S3::Vendor::Generic->new( 
         host => $self->{endpoint},
         use_virtual_host => 0,
         default_region => $self->{region},
         authorization_method => 'Net::Amazon::S3::Signature::V4',
     );
   
    $self->{s3} = Net::Amazon::S3->new(
        authorization_context => $self->{auth},
        retry => 1,
        vendor => $self->{vendor});
``` 

While I think this should work, or at least give an authentication error, I get:

```
Use of uninitialized value in concatenation (.) or string at /stack/local/lib/perl5/Net/Amazon/S3/Signature/V4Implementation.pm line 200, <DATA> line 71.
S3 Get error: SignatureDoesNotMatch - The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Any hint on what I might be doing wrong?
Thanks in advance.

**Comment by happy-barney** [comment]
Only way I managed to get `undef` at mentioned line 200 was with request containing explicit `X-Amz-SignedHeaders` query parameter :-(

Can you intercept `_canonical_request` method as well as `_headers_to_sign` response? eg:
```
my $canonical_request = \& Net::Amazon::S3::Signature::V4Implementation::_canonical_request;
my $guard = Sub::Override::->new (q (Net::Amazon::S3::Signature::V4Implementation::_canonical_request) => sub {
    print Data::Dumper::Dumper ($_[1]);
   goto $canonical_request;
});

my $headers_to_sign = \& Net::Amazon::S3::Signature::V4Implementation::_headers_to_sign;
my $guard = Sub::Override::->new (q (Net::Amazon::S3::Signature::V4Implementation::_headers_to_sign) => sub {
    my @list = $headers_to_sign->(@_);
    print Data::Dumper::Dumper (\@list);
    return @list;
});
```

Dump of request should contain `HTTP::Headers` instance having all headers returned by `_headers_to_sign` defined.

**Comment by ambs** [comment]
I cannot believe that it was a stupid case error on an environment variable that was causing the key to be empty.
I am sorry for my stupidity.
Thanks for the help,
Alberto

**Comment by happy-barney** [comment]
no problem :-) can you please describe how that empty value got propagated into `V4Implementation` ?
As far as it is possible (thanks for noticing that) I'd like to think about a way how to report it better.

**Comment by ambs** [comment]
Hello.
Basically:
```
   $self->{auth} = Net::Amazon::S3::Authorization::Basic->new(
       aws_access_key_id => $self->{access_key},
       aws_secret_access_key => $self->{secret_key}
    );
```

the `$self->{secret_key}` was undef :-)
