### ISSUE TITLE
Empty bucket lists as of .80?

### ISSUE THREAD

**Issue by sreid55** [rustyconover/net-amazon-s3#14]
Sorry this is probably not an issue, but I'm stuck.. After upgrading from .60 to .80, all of my bucket list attempts return empty lists.   Trying to figure out what might have changed.   Not using any prefix, can't get any lists via $s3->list_bucket, $s3->list_bucket_all, $bucket->list, $bucket->list_all.   Tried on two buckets, one with 'everyone' perms.   Reverting to .60, same code works fine.
Scott

**Comment by rustyconover** [comment]
Which region are you hosting the buckets in?

Sent from my iPhone

On Jan 21, 2016, at 9:52 PM, sreid55 <notifications@github.com> wrote:

Sorry this is probably not an issue, but I'm stuck.. After upgrading from
.60 to .80, all of my bucket list attempts return empty lists. Trying to
figure out what might have changed. Not using any prefix, can't get any
lists via $s3->list_bucket, $s3->list_bucket_all, $bucket->list,
$bucket->list_all. Tried on two buckets, one with 'everyone' perms.
Reverting to .60, same code works fine.
Scott

—
Reply to this email directly or view it on GitHub
<https://github.com/rustyconover/net-amazon-s3/issues/14>.

**Comment by sreid55** [comment]
"Oregon"  I don't recall this name being used when we set them up a few years ago, but that's what the AWS console says they are in now.

**Comment by rustyconover** [comment]
You should see the changelog of the module, you will probably need to set a
new endpoint url, to point at the s3 endpoint of Oregon.

Hth,

Rusty

Sent from my iPhone

On Jan 22, 2016, at 8:57 AM, sreid55 <notifications@github.com> wrote:

"Oregon" I don't recall this name being used when we set them up a few
years ago, but that's what the AWS console says they are in now.

—
Reply to this email directly or view it on GitHub
<https://github.com/rustyconover/net-amazon-s3/issues/14#issuecomment-173927270>
.

**Comment by sreid55** [comment]
Yep - That was it.   Specifiying host=>"s3-us-west-2.amazonaws.com" (from the list here: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) did the trick.
Thanks!
