### ISSUE TITLE
Canonical User ID (OwnerID) might not be 64 hexdigit on non-AWS S3

### ISSUE THREAD

**Issue by robbat2** [rustyconover/net-amazon-s3#18]
It was reported to  Ceph that Net::Amazon::S3 didn't work with Ceph RGW, as Net::Amazon::S3::Client was expecting the canonical user ID (OwnerID in some parts of the S3 documentation) to be 64 hex characters exactly, and Ceph RGW allows a lot more freedom in that string (printable ascii, length > 0).

Ceph issue link: http://tracker.ceph.com/issues/16806

The S3 specifications are vague on the exact requirements of the string, and describe it in only two places

http://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html says

> The canonical user ID is a long string, such as
> 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be.

 http://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example4.html says

> The canonical user ID is the Amazon S3–only concept. It is s
> 64-character obfuscated version of the account ID.

**Comment by TJC** [comment]
I can confirm I have had this problem too -- and it's also present when using Minio S3.

**Comment by TJC** [comment]
A simple fix we're using is:

https://github.com/strategicdata/net-amazon-s3/commit/1b9b52d3aece937cb853b1f9f25bb3bab2713310

**Comment by ranguard** [comment]
As a side note https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL has been released - testing would be appreciated

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.83 - please comment if this does not fix it
