### ISSUE TITLE
specifying host for S3 compaitable servers

### ISSUE THREAD

**Issue by rmallah** [rustyconover/net-amazon-s3#22]
Looks like a host parameter was introduced , but its not there any more for the
main constructor. How can this module be used for connecting non-AWS S3
compatible servers ?

**Comment by ranguard** [comment]
Please review - https://metacpan.org/pod/release/LLAP/Net-Amazon-S3-0.81-TRIAL/lib/Net/Amazon/S3.pm#host ? - or do you mean some where else?

If you reply I'll reopen!
