### ISSUE TITLE
Secure should be the default

### ISSUE THREAD

**Issue by zostay** [rustyconover/net-amazon-s3#23]
This is 2017. Secure should be default. I recommend it become the default in the next release.

**Comment by ranguard** [comment]
Sounds good.. I'll take a patch if you (or anyone) would like to submit one, requires tests and allowing users to deactivate the secure mode.

Thank you

**Comment by ranguard** [comment]
As a side note https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL has been released - testing would be appreciated

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.83 - please comment if this does not fix it

**Comment by bdeutsch-heise** [comment]
Works, thanks!
