### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by eon8ight** [rustyconover/net-amazon-s3#28]
CPAN upgraded to 0.82 over the weekend, even though it seems 0.82 hasn't been released yet. This bug may exist in 0.81. Calling `Net::Amazon::S3::Bucket->add_key_filename()` silently fails, and the `errstr` is this:

`The request signature we calculated does not match the signature you provided. Check your key and signing method.`

**Comment by ranguard** [comment]
Sorry I'm new to released on Github - forgot to do it. @branislav-zahradnik-gdc ideas on the signature?

**Comment by branislav-zahradnik-gdc** [comment]
@eon8ight can you please share:
- which region is your bucket ?
- value of `key` ?

I came around this error as well, can be either unexpected redirect or wrong evaluation of key path.

**Comment by eon8ight** [comment]
@branislav-zahradnik-gdc 
The region is `us-east-1` and one of the keys used is `/tmp/customer/transient/20180710_100517.fb74f6066c4623f970f7a84f9b437fe05b44bd1b302918.20828449.csv`.

**Comment by branislav-zahradnik-gdc** [comment]
thank you, I'll look into it

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.83 - please comment if this does not fix it
