### ISSUE TITLE
New region detection mechanism breaks non-Amazon hosts

### ISSUE THREAD

**Issue by bdeutsch-heise** [rustyconover/net-amazon-s3#29]
The recent version 0.82 with pull request #27 unfortunately breaks this module for non-Amazon S3 hosts (RADOS et al) with an error like the following:

```
Attribute (region) does not pass the type constraint because: Validation failed for 'Str' with value undef at reader Net::Amazon::S3::HTTPRequest::region
```

Before 0.82, the region happened to default to a defined bucket, but the current code returns `undef` if the header is missing.

Would it be possible to add a fallback value, like `none`, if the header is missing, or to relax the requirements on bucket regions?

**Comment by branislav-zahradnik-gdc** [comment]
bucket region is evaluated only in case of Signature 4.
Changing default authorization method so it will be Signature 4 only for amazonaws host.

**Comment by ranguard** [comment]
@branislav-zahradnik-gdc I didn't see that commit in the PR I merged... guessing on the way :) - I'll hold off on a release for now :)

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.83 - please comment if this does not fix it
