### ISSUE TITLE
[0.84] Subroutine BUILD redefined at /usr/local/lib/perl5/site_perl/5.24.1/Net/Amazon/S3.pm line 95

### ISSUE THREAD

**Issue by sdt** [rustyconover/net-amazon-s3#33]
In v0.84 I get this warning:

`Subroutine BUILD redefined at /usr/local/lib/perl5/site_perl/5.24.1/Net/Amazon/S3.pm line 95`

Seems there is actually two BUILD subs in S3.pm

https://github.com/rustyconover/net-amazon-s3/blob/0.84/lib/Net/Amazon/S3.pm#L176

and

https://github.com/rustyconover/net-amazon-s3/blob/0.84/lib/Net/Amazon/S3.pm#L281

**Comment by branislav-zahradnik-gdc** [comment]
oops, thanks for spotting that => pull request #34

**Comment by fschlich** [comment]
can be closed now that  #34  has been merged, no?
