### ISSUE TITLE
set_acl fails with error

### ISSUE THREAD

**Issue by t-postel** [rustyconover/net-amazon-s3#39]
I'm using dreamhost cloud servers. They had had a west coast cloud server and moved to an east coast server. The west coast server worked fine but the east coast server fails on set_acl. I've complained to them.
$res = $bucket->set_acl({
                key       => $Path,
                acl_short => 'public-read',
             });
fails with $res returning 0 and $bucket->err set to 'MissingContentLength'
same failure with acl set to private.

**Comment by ealarcong** [comment]
This still happens, this a work around i found
my $conn = Net::Amazon::S3->new({
        aws_access_key_id     => $access_key,
        aws_secret_access_key => $secret_key,
        secure                => 1,
        retry                 => 1,
});

$conn->ua->default_header('Content-Length' => "0");

my $bucket = $conn->bucket($bucket_name);
$bucket->set_acl({
        key       => 'hello.txt',
        acl_short => 'public-read',
});

**Comment by happy-barney** [comment]
Fixed in v0.92, `Content-Length: 0` header is now enforced
