### ISSUE TITLE
Class doesn't support object tagging. Must have feature.

### ISSUE THREAD

**Issue by evgeny156** [rustyconover/net-amazon-s3#44]
It very bad :(

**Comment by happy-barney** [comment]
Tagging support added in v0.92

**Comment by vaskozl** [comment]
Can we re-open this issue?

There are quite a few things which I believe are missing:

* tags are not retrieved (like how metadata is retrieved) in the Objects on GET
* tags can not be set via the initial PUT, requiring `add_tags` which incurs the cost of an extra PUT request. At present there is no way to set the `x-amz-tagging` header as one can not pass extra headers into the `_put` method.
* add_tags  doesn't actually *add* tags, it use PutObjectTagging which replaces all tags
