### ISSUE TITLE
Failed to upgrade from V.80 to V.86

### ISSUE THREAD

**Issue by ajudeikin** [rustyconover/net-amazon-s3#52]
[Issue_with_upgrading_to_new_Version.docx](https://github.com/rustyconover/net-amazon-s3/files/3142675/Issue_with_upgrading_to_new_Version.docx)
-----------------------------------------------------------------------------------------------------

Thanks in advance.

Arkady Judeikin
LoyaltyOne, Toronto

**Comment by choroba** [comment]
I am trying to use the following code to upload a file to an S3 bucket:

```perl
use Net::Amazon::S3;

my $s3 = Net::Amazon::S3->new(
        { aws_access_key_id     => '********************',
          aws_secret_access_key => '********************',
        }
);

$bucket = $s3->bucket('**********');

$bucket->add_key_filename( 
         'rkd/PNTS0014.csv',  'C:\rkd\PNTS0014.csv',
       #{ "x-amz-server-side-encryption" => 'AES256' }
        { "x-amz-server-side-encryption" => 'aws:kms'}
)
or print $s3->err . ": " . $s3->errstr;
```

It works fine with  `AES256`. But when I try  `aws:kms` - it fails with the message:

> InvalidArgument: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.

I was advised to upgrade the Net::Amazon::S3 from V.80 to a later version.
I followed your instructions:

```
cpan App::cpanminus
cpanm Net::Amazon::S3
```

Unfortunately the installation failed:

> -> FAIL Installing the dependencies failed: Module 'XML::LibXML' is not installed, Module 'XML::LibXML::XPathContext' is not installed
> -> FAIL Bailing out the installation for Net-Amazon-S3-0.86.

Also there are few other failures showing up in the build.log.

Can you please advise how to resolve the issue?

How can I install previous versions, e.g. Net-Amazon-S3-0.83 ?

**Comment by happy-barney** [comment]
Hi @ajudeikin 

as mentioned in your output problem is with `XML::LibXML` (dependency). I'd suggest to install that one first with more verbose mode, solve its issues and than try to install `Net::Amazon::S3` again.
