### ISSUE TITLE
authorization_method hardcoded in ListAllMyBuckets.pm

### ISSUE THREAD

**Issue by nhilterbrand** [rustyconover/net-amazon-s3#54]
In the module ListAllMyBuckets.pm, the authorization_method is hardcoded to use V2:

sub http_request {
    my $self    = shift;
    return $self->_build_http_request(
        use_virtual_host => 0,
        authorization_method => 'Net::Amazon::S3::Signature::V2',
    );
}

This causes this operation to fail when V4 is required

**Comment by ranguard** [comment]
@happy-barney - thoughts?

**Comment by happy-barney** [comment]
it's a bug, already fixed in my dev branch (along other changes). Fix is simple, Amazon will drop V2 next month, I'll create pull request

**Comment by ranguard** [comment]
As usual you are fantastic - thank you

**Comment by happy-barney** [comment]
Fixed in #58
