### ISSUE TITLE
Issue with Google Cloud Storage S3 and parsing of XML list

### ISSUE THREAD

**Issue by michal-josef-spacek** [rustyconover/net-amazon-s3#55]
There is issue with GCS S3 and parsing of XML list.
Issue is in fact, that AWS and GCS returns different XML namespace.
AWS returns:
`<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">`
GCS returns:
`<ListBucketResult xmlns='http://doc.s3.amazonaws.com/2006-03-01'>`

And Net::Amazon::S3 module has hardcoded `$xpc->registerNs( 's3', 'http://s3.amazonaws.com/doc/2006-03-01/' );`

**Comment by tupinek** [comment]
https://github.com/rustyconover/net-amazon-s3/pull/56
