### ISSUE TITLE
SigV4 protocol not working

### ISSUE THREAD

**Issue by TomRaney** [rustyconover/net-amazon-s3#65]
I'm encountering an exception during upload where the etag isn't matching the md5 file hash.  My understanding of the SigV4 protocol is that this comparison shouldn't be happening, because the etag isn't the md5 sum in the SigV4 case.  The file is uploading properly but it's the comparison at the very end that is failing on this line:

https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Client/Object.pm#L236  

We're not explicitly setting the protocol but it appears that the library will adopt SigV4 when the host is "s3.amazonaws.com", which is the value we're using.

Our usage:

```
$self->s3(Net::Amazon::S3->new({
        aws_access_key_id     => $aws_access_key_id,
        aws_secret_access_key => $aws_secret_access_key,
        host                  => $self->server(),
        retry                 => $self->auto_retry_on_s3_failures(),
        secure                => $self->secure(),
}));

...

$object->put_filename($local_filename);
```

Is this a bug or is there flaw in our usage?

```
Failed to upload foo.txt: Corrupted upload got 9a8ec72be496b8837bf31095bf32cb3c expected 006fb2335c90aa65afabf0cfd56a3508 at /linux/lib/perl5/Net/Amazon/S3/Client/Object.pm line 236.
        Net::Amazon::S3::Client::Object::_put('Net::Amazon::S3::Client::Object=HASH(0x14b60ac0)', 'CODE(0xed2fd08)', 100605726, '006fb2335c90aa65afabf0cfd56a3508') called at /linux/lib/perl5/Net/Amazon/S3/Client/Object.pm line 249
        Net::Amazon::S3::Client::Object::put_filename('Net::Amazon::S3::Client::Object=HASH(0x14b60ac0)',  ...
```

**Comment by sergot** [comment]
I'm facing the same issue, @TomRaney did you manage to find a solution? :)

**Comment by happy-barney** [comment]
@TomRaney @sergot 

quickfix for this issue will be to specify Signature::V2 manuallyduring S3 instance construction:
```
   authorization_method => 'Net::Amazon::S3::Signature::V2'
```
