### ISSUE TITLE
content iterator not reset before retry (was issue #35 on the pfig repo)

### ISSUE THREAD

**Issue by jdv** [rustyconover/net-amazon-s3#7]
Hello,

If I remember correctly it should be relatively easy to repo by
causing a PUT that uses _content_sub (the aforementoned
iterator) to fail and retry.  I don't work where this was showing
up anymore and I don't have time right now to write up the test
case.  If you fail to repro it I can look into it later when I have time.

Also,

Why was the former issue deleted after correspondence was sought.
I got an email from you (Rusty Conover) saying "@jdv: can you supply
some example code to reproduce this error?" on May 17th.
Sorry for the several month delay - been a bit distracted.

-jdv

**Comment by rustyconover** [comment]
Hi,

I believe pfig closed all of pending issues in the old net-amazon-s3 repo a few months ago to signal he wasn't working on the code anymore.

Not that the problem was resolved.

Rusty

**Comment by ranguard** [comment]
Haven't had a test case - do open another issue if you can re-produce
