### ISSUE TITLE
Can't call method "region"

### ISSUE THREAD

**Issue by EdwardsMike** [rustyconover/net-amazon-s3#80]
Hi! I'm new to this module (and to working with AWS S3), but when I attempt to simply fetch a list of buckets, I get the error "Can't call method "region" on an undefined value at /usr/local/share/perl/5.22.1/Net/Amazon/S3/HTTPRequest.pm line 49." I have been given both an access key and a secret key, and there was mention of IAM with those creds but when I toggle use_iam_role, I get a "No IAM credentials received..." error. Any help would be appreciated.

**Comment by happy-barney** [comment]
region problem already fixed in #78 

regarding IAM, problem:
mentioned error message comes from `VM::EC2::Security::CredentialCache` and unfortunately I have no experience with that :-(

**Comment by EdwardsMike** [comment]
Thanks. I installed using cpan and perldoc says I'm running v0.89 but I will download and install from here.
