### ISSUE TITLE
release to CPAN of bugfixes?

### ISSUE THREAD

**Issue by samsmith** [rustyconover/net-amazon-s3#84]
I’m hitting a bug in Net::Amazon::S3 which has been fixed in github but not pushed out to CPAN: #78
(all my S3 scripts break because of the region bug)

If there’s no reason that there’s not been a CPAN update, can you push a release to CPAN?

**Comment by happy-barney** [comment]
Reason is while contemplating how to handle future of `Net::Amazon::S3::Authorization::IAM` I just forgot to do it, sorry.

Thanks for reminding

**Comment by samsmith** [comment]
thanks for this.  

From the new release, I'm seeing random errors in scripts from Moose, which are resolved by patching S3.pm like this:
around BUILDARGS => sub {
        my ($orig, $class, $args) = @_;
        my %args;
        if (defined $args ) {%args= %$args;}

(not the prettiest change, but it's where it started to work). I'm not sure if it's something worth looking into or not, but it's line 140 of S3.pm

**Comment by happy-barney** [comment]
what kind of error? "odd number of elements" ?

**Comment by samsmith** [comment]
That, or if you had region(?) defined, a different error.

I've some long running stuff going on that machine right now, but this might work to reproduce (it's from a test script).

my $s3 = Net::Amazon::S3->new(
      {   aws_access_key_id     => "AAA",
          aws_secret_access_key => "AAA",  } );
my $client = Net::Amazon::S3::Client->new( s3 => $s3 );
my $bucket=$client->bucket( name => 'AAA'); 
my $this_object = $bucket->object(
	key          => "test.html",
	content_type => 'text/html',
);
$this_object->put_filename("tmp/test.pdf");

**Comment by happy-barney** [comment]
ok, thanks, it's broken construction of object with hashref parameter.

Thanks for reporting, fixed in 0.91
