### ISSUE TITLE
Net-Amazon-S3-0.90 uses Scalar::Util without loading it

### ISSUE THREAD

**Issue by ppisar** [rustyconover/net-amazon-s3#85]
Net-Amazon-S3-0.90 calls Scalar::Util::blessed() at lib/Net/Amazon/S3/Role/Bucket.pm:15, but it does not requiere nor use Scalar::Util. It probably only works, because it's loaded transitively by another module. When the another module changes, it will stop working. Please load the module explicitly.

**Comment by happy-barney** [comment]
Thanks for reporting, fixed in 0.91
