### ISSUE TITLE
Calls to undefined methods in 0.92 & 0.93 releases

### ISSUE THREAD

**Issue by veryrusty** [rustyconover/net-amazon-s3#87]
There are calls to `_fetch_response` which doesn't appear to be defined anywhere (introduced in the v0.92 release):
* https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Client/Bucket.pm#L101
* https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Client/Object.pm#L129
* https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Client/Object.pm#L143

Were these meant to be calls to `_perform_operation` ?

**Comment by happy-barney** [comment]
Thanks for spotting this, appeared in still untested code :-(

**Comment by veryrusty** [comment]
Thanks for the quick fix!
