### ISSUE TITLE
Presigned URLs for non-GET requests

### ISSUE THREAD

**Issue by veryrusty** [rustyconover/net-amazon-s3#89]
We have a use-case where we need to generate a presigned url for uploading an object to S3. There are some docs on this, eg: https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

The method (eg PUT) is part of signing algorithm, however the V4Implementation for presigning urls is currently hard-coded to construct a GET request: https://github.com/rustyconover/net-amazon-s3/blob/master/lib/Net/Amazon/S3/Signature/V4Implementation.pm#L136

Can the `http_request->method` be passed into the implementation to generate presigned urls for other request methods ?

**Comment by happy-barney** [comment]
Preliminary implementation available in my development branch - it works but I'm not happy with `Client::Object`
I'll take day or to to think about it ... maybe I came with better idea, or I'll just release it as it is now.

**Comment by veryrusty** [comment]
I've had a quick look over a3fe162, it certainly covers our use-case. Thanks for looking at this so quickly!

**Comment by happy-barney** [comment]
Released as v0.97.
