### ISSUE TITLE
Why host for non-us buckets must now be specified esplicitly?

### ISSUE THREAD

**Issue by lordarthas** [rustyconover/net-amazon-s3#9]
I have some S3 buckets in Ireland. With version 0.59 or so of Net::Amazon::S3 everything was fine but now with 0.89 I need to explicitly pass:

host => s3-eu-west-1.amazonaws.com

as initialization parameter.

Is this a wanted behaviour? It doesn't seem so handy.

**Comment by rustyconover** [comment]
It not so handy that is true.

The existing bucket region detection code was incorrect so I went back to a
version that doesn't have some very glaring bugs that relied on bad regular
expressions.

Of course I'm open to improvements in this code.

Thanks,

Rusty

**Comment by lordarthas** [comment]
Hello!

Understood. Can I maybe provide a patch for the documentation to make the thing a bit clearer?

Thanks,
Michele.

**Comment by ivanmitic-bx** [comment]
@lordarthas,
Can you please paste your instructions here?
While host => "s3-us-west-2.amazonaws.com"' works well for bucket in Oregon, the similar thing,
host => "s3-eu-central-1.amazonaws.com" fails with:
InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

Thanks,
Ivan

**Comment by lordarthas** [comment]
Hello!

I'm using:

host => 's3-eu-west-1.amazonaws.com'

and works fine (bucket is in Ireland). Never tried EU Central (which I assume is Frankfurt).

Michele.

**Comment by ivanmitic-bx** [comment]
@lordarthas, thanks.
@rustyconover,
Does the lib support AWS4-HMAC-SHA256 (so called V4) authorization? If so, is there any docs?
If V4 is not supported, is there a plan to? As it seems "new" regions (from 2014 and newer) will only support that, so lib can't really be used for buckets located there.

Thanks,
Ivan.

**Comment by JaSei** [comment]
Hello, I have same problem and solution for me (I only need download objects) is my module - https://metacpan.org/pod/Net::AmazonS3::Simple maybe will be help for you....

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/Net-Amazon-S3-0.81-TRIAL released please test and open ticket if there are any issues - now supports V4 authorization
