### ISSUE TITLE
Object->put_file(). Verify the object's integrity during the upload

### ISSUE THREAD

**Issue by targzeta** [rustyconover/net-amazon-s3#90]
Hi,
is it possible to check the object's integrity during the upload as described to [this link](https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/)?

I see that the aws cli sets the 'Content-MD5' within the headers of the request.

Best regards,
Emanuele

**Comment by happy-barney** [comment]
Hi @targzeta, this feature is currently available only via `Client` interface. `S3` interface was considered deprecated. Currently I'm working on features synchronization with `S3` being procedural and data structures oriented whereas `Client` will be OOP.

**Comment by targzeta** [comment]
Hi,
I have seen the code. I guess that the put_filename() sets the md5sum automatically. It's right?

For multipart upload, the put_part() doesn't seem that made the same thing. This snippet, however, works fine:
```
use Digest::MD5 qw(md5_base64);
my $md5_base64 = md5_base64($chunk_content) . '==';
my $put_part_response = $s3_object->put_part(
    upload_id   => $upload_id,
    part_number => $i,
    value       => $chunk_content,
    headers     => {'Content-MD5'    => $md5_base64},
);
```
Emanuele

**Comment by targzeta** [comment]
Good! I'll stay tuned :+1: 

It might be useful too a wrapper method with filePath and (optional) chunkSize as signature. If chunkSize is undefined we could use put_file or {initiate_multipart_upload, put_part, complete/abort_multipart_upload} based upon the file size (> 5GiB?) with a default chunkSize (8 MiB?). If chunkSize is defined, we could force the {initiate...} after checking chunkSize size (> 5MiB?).

Best regards,
Emanuele

**Comment by happy-barney** [comment]
That's my plan :-) But there are S3 implementations without multipart support (along with unlimited chunk size) so I have to first come with good abstraction :-( (not available yet)

Anyway, thanks for usage and reports.
