### ISSUE TITLE
Compatibility issues with DigitalOcean Spaces

### ISSUE THREAD

**Issue by meylingtaing** [rustyconover/net-amazon-s3#95]
Hi, apologies if this should actually be three issues, but I'm trying to use Net::Amazon::S3 to interface with the [Digital Ocean Spaces API](https://developers.digitalocean.com/documentation/spaces/) , which should be Amazon s3 compatible. I ran into a few problems with this.

I used Net::Amazon::S3::Vendor::Generic to create a custom vendor, and I set a `default_region`, but when I tried to say, list all buckets in my space, it was defaulting to the 'us-east-1' region. I noticed that 'us-east-1' is hardcoded in a few places. Can this be changed to use the `default_region` instead?

I also noticed that this will automatically set a Content-Length header with value 0 if there is no explicit content length. This happens when you try to list all buckets. This was making my request to list all buckets (a GET request) fail authentication. When I made this change, it worked. Is there a reason why we need to explicitly set content length to 0 here?

```diff --git a/lib/Net/Amazon/S3/HTTPRequest.pm b/lib/Net/Amazon/S3/HTTPRequest.pm
index f790eac..ae7cba1 100644
--- a/lib/Net/Amazon/S3/HTTPRequest.pm
+++ b/lib/Net/Amazon/S3/HTTPRequest.pm
@@ -89,7 +89,8 @@ sub _build_request {
        my $uri          = $self->request_uri;
 
        my $http_request = HTTP::Request->new( $method, $uri, $http_headers, $conten
-       $http_request->content_length (0) unless $http_request->content_length;
+
+       #$http_request->content_length (0) unless $http_request->content_length;
 
        return $http_request;
 }
```

Finally, the responses that I was getting back had content type "text/xml", and I noticed that `is_xml_content` specifically checks for "application/xml". Can we make this accept text/xml as well?

**Comment by happy-barney** [comment]
I tried to provide fix for this issue, vendor should be created with:
```
new Net::Amazon::S3::Vendor (
    enforce_empty_content_length => 0,
)
```

I'm quite stuck with tests right now, so its available only in my branch https://github.com/rustyconover/net-amazon-s3/compare/master...happy-barney:hpb-dev-issues

**Comment by happy-barney** [comment]
changes uploaded to CPAN (sorry for delay)
